apiVersion: v1
kind: ConfigMap
metadata:
  name: linkyboard-db-config
  namespace: {{ .Values.namespace }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.database.url }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: {{ .Values.database.driverClassName }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: none
  SPRING_JPA_SHOW_SQL: "true"
