apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkyboard-be
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: linkyboard-be
  template:
    metadata:
      labels:
        app: linkyboard-be
    spec:
      containers:
      - name: linkyboard-be
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - configMapRef:
            name: linkyboard-db-config
        - secretRef:
            name: linkyboard-db-secret
