apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkyboard-be
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: linkyboard-be
  template:
    metadata:
      labels:
        app: linkyboard-be
    spec:
      containers:
      - name: linkyboard-be
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: linkyboard-be-secret
              key: db_url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: linkyboard-be-secret
              key: db_username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linkyboard-be-secret
              key: db_password
