apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: linkyboard-ai-route
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoint }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Values.service.name }}
          namespace: {{ .Values.namespace }}
          port: {{ .Values.service.port }}